### ISSUE TITLE
URL da Search API

### ISSUE THREAD

**Issue by chambber** [Yokutto/Anime-Sync-API#2]
Para utilizar essa API é obrigatório o uso da `/` no final. Por exemplo: `https://api.animesync.tv/v3/search/teste/`, sendo que se não for informada, é retornado o erro 403.

Queria sugerir a não obrigatoriedade dessa `/`.

**Comment by Yokutto** [comment]
O final da barra "/" serve para determinar o fim de uma query em nossa aplicação e não iremos remover. Você pode acrescentar opções na API apos a barra, como também pode pesquisar uma barra "/" ou qualquer outro simbolo utilizando o URL Encoding: https://en.wikipedia.org/wiki/Percent-encoding

**Comment by chambber** [comment]
Ah, entendi o uso dela, estava testando a API e um estudo e fiquei uns minutos com esse retorno até entender que era por causa da `/`. Então talvez algum aviso na Wiki?

**Comment by chambber** [comment]
Não tem relação com isso, mas terá thumbnails para os animes também?

**Comment by Yokutto** [comment]
Geralmente na maioria das API's de servicos na internet a / termina a query, entao deve ser comum alguem achar isso. Os animes ira conter todas as informacoes: nome, descricao, fansub, imagem, ID's dos episodios  e numero de episodios postados atualmente. Ela nao ira conter: o status do anime (Sendo lancamento ou nao), categorias separadas, sinopse separada, visualizacao total do anime (soma das visualizacoes dos episodios).
